#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include "basico.c"
int ordenamatriz(int **mat,int n,int m);
int ordenalinha(int **mat, int n, int m);
int ordenacoluna(int **matriz, int n, int m);
int checa(int **matriz, int n, int m);
int entradamatrizint(int **matriz,int n,int m);
int main()
{

    //system("clear");
    srand(time(NULL));
    printf("\n\n\t\tgenerating and sorting matrix randomly. recursive method!\n\n");
    int **MatrizA;
    int i,j,n;
    printf("\nEnter the matrix order: ");
	scanf("%d",&n);
	printf("\n");
	if (n == 0) {printf("\nNull Dimension\nFinished Program\n");system("pause");return 1;}
     /*Alocação de Memória para Matrizes*/
    if(!(MatrizA = alocacaoint(n,n)))
    {
        printf("\nCould not allocate memory for Array A\nFinished Program\n");
        return 1;
    }
    /*Entrada da Matriz A*/
    entradamatrizint(MatrizA,n,n);
    printf("\nmatrix generated by the program:\n\n ");
    imprimematrizint(MatrizA,n,n);
     printf("\nmatrix ordered by the program: \n");
    ordenamatriz(MatrizA,n,n);
     printf("\nmatrix ordered by row: \n");
     ordenalinha(MatrizA,n,n);
     printf("\nmatrix ordered by colunm: \n");
     ordenacoluna(MatrizA,n,n);
    getchar();
    return 0;
}
int entradamatrizint(int **matriz,int n,int m)
{

        int a,i,j;
        int r=n*n;

        for (i=0;i<n;i++) for(j=0;j<m;j++)
        {
            a=rand()%r;
            matriz[i][j]=a;
            checa(matriz,n,a);}
        return 0;
}
int checa(int **matriz, int dim, int num ){
    int  i, j, cont=0, r=dim*dim;
    for(i=0; i<dim; i++)
    for(j=0; j<dim;j++)
    if(num==matriz[i][j]){
    cont++;
if(cont>1){
        matriz[i][j]=rand()%r;checa(matriz,dim,matriz[i][j]);
}
    }

    return 0;}
int ordenamatriz(int **mat,int n,int m){
int k,l,temp=0,i,j;
int matriz[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz[i][j]=mat[i][j];
}
for(i=0; i<n; i++){
              for(j=0; j<n; j++){
                 for(k=0; k<n; k++){
                    for(l=0;l<n;l++){
                    if(matriz[i][j]< matriz[k][l]){
                       temp= matriz[i][j];
                       matriz[i][j]= matriz[k][l];
                       matriz[k][l]=temp;
                    }
                 }
              }
           }}
           for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz[i][j]);
           printf("\n");
           }
           }
int ordenalinha(int **mat,int n,int m){
int var1,var2,i,j;
int matriz[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz[i][j]=mat[i][j];
}
for(i=0; i<n; i++){
              for(j= m-1; j>=0; j--){
                 for(var1= j-1; var1>=0; var1--){
                    if(matriz[i][j]< matriz[i][var1]){
                       var2= matriz[i][j];
                       matriz[i][j]= matriz[i][var1];
                       matriz[i][var1]=var2;
                    }
                 }
              }
           }
           for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz[i][j]);
           printf("\n");
           }
           }
int ordenacoluna(int **matriz, int n, int m){
int var1,var2,i,j;
int matriz_aux[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz_aux[i][j]=matriz[i][j];
}
for(j=m-1; j>=0; j--){
                 for(i= n-1; i>=0; i--){
                     for(var1= i-1; var1>=0; var1--){
                         if(matriz_aux[i][j]< matriz_aux[var1][j]){
                            var2= matriz_aux[i][j];
                            matriz_aux[i][j]=matriz_aux[var1][j];
                            matriz_aux[var1][j]=var2;
                         }
                     }
                 }
              }
              for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz_aux[i][j]);
           printf("\n");
           }}
