#include<stdio.h>
#include<time.h>
#include<stdlib.h>
#include<math.h>
#include<string.h>
#include "basico.c"
int ordenamatriz(int **mat,int n,int m);
int ordenalinha(int **mat, int n, int m);
int ordenacoluna(int **matriz, int n, int m);
int main()
{
    //system("clear");
    srand(time(NULL));
    printf("\n\n\t\tgenerating and sorting matrix randomly. method: 'Bubble Sort'\n\n");
    int **MatrizA;
    int i,n;
    printf("\nEnter the matrix order: ");
	scanf("%d",&n);
	if (n == 0) {printf("\nNull Dimension\nFinished Program\n");system("pause");return 1;}
    if(!(MatrizA = alocacaoint(n,n)))
    {
        printf("\nCould not allocate memory for Array A\nFinished Program\n");
        return 1;
    }
    entradamatrizint(MatrizA,n,n);
    printf("matrix generated by the program: \n");
    imprimematrizint(MatrizA,n,n);
    printf("\nmatrix ordered by the program: \n");
    ordenamatriz(MatrizA,n,n);
    printf("\nmatrix ordered by row: \n");
    ordenalinha(MatrizA,n,n);
    printf("\nmatrix ordered by colunm: \n");
    ordenacoluna(MatrizA,n,n);
    getchar();
    return 0;
}
int entradamatrizint(int **numbers,int n,int m)
{
 int a,b,i,j,c=-1;
for (i = 0; i <n ; i++)for(j=0;j<n;j++){
c++;
numbers[i][j]= c;}
for(i=0;i<n;i++){
    for(j=0;j<n;j++){
        a=rand()%n;b=rand()%n;
        int temp=numbers[i][j];
        numbers[i][j]=numbers[a][b];
        numbers[a][b]=temp;}}
}
int ordenamatriz(int **mat,int n,int m){
int k,l,temp=0,i,j;
int matriz[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz[i][j]=mat[i][j];
}
for(i=0; i<n; i++){
              for(j=0; j<n; j++){
                 for(k=0; k<n; k++){
                    for(l=0;l<n;l++){
                    if(matriz[i][j]< matriz[k][l]){
                       temp= matriz[i][j];
                       matriz[i][j]= matriz[k][l];
                       matriz[k][l]=temp;
                    }
                 }
              }
           }}
           for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz[i][j]);
           printf("\n");
           }
           }
int ordenalinha(int **mat,int n,int m){
int var1,var2,i,j;
int matriz[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz[i][j]=mat[i][j];
}
for(i=0; i<n; i++){
              for(j= m-1; j>=0; j--){
                 for(var1= j-1; var1>=0; var1--){
                    if(matriz[i][j]< matriz[i][var1]){
                       var2= matriz[i][j];
                       matriz[i][j]= matriz[i][var1];
                       matriz[i][var1]=var2;
                    }
                 }
              }
           }
           for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz[i][j]);
           printf("\n");
           }
           }
int ordenacoluna(int **matriz, int n, int m){
int var1,var2,i,j;
int matriz_aux[n][n];
for(i=0;i<n;i++)for(j=0;j<n;j++){
matriz_aux[i][j]=matriz[i][j];
}
for(j=m-1; j>=0; j--){
                 for(i= n-1; i>=0; i--){
                     for(var1= i-1; var1>=0; var1--){
                         if(matriz_aux[i][j]< matriz_aux[var1][j]){
                            var2= matriz_aux[i][j];
                            matriz_aux[i][j]=matriz_aux[var1][j];
                            matriz_aux[var1][j]=var2;
                         }
                     }
                 }
              }
              for(i=0; i<n; i++){
               printf("\n");
               for(j=0; j<n; j++)printf("%d\t", matriz_aux[i][j]);
           printf("\n");
           }

        }
